// Generated by gencpp from file dgvmsg/Encounter.msg
// DO NOT EDIT!


#ifndef DGVMSG_MESSAGE_ENCOUNTER_H
#define DGVMSG_MESSAGE_ENCOUNTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dgvmsg
{
template <class ContainerAllocator>
struct Encounter_
{
  typedef Encounter_<ContainerAllocator> Type;

  Encounter_()
    : header()
    , devadd(0)
    , now()
    , encounter(0)  {
    }
  Encounter_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , devadd(0)
    , now()
    , encounter(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _devadd_type;
  _devadd_type devadd;

   typedef ros::Time _now_type;
  _now_type now;

   typedef uint32_t _encounter_type;
  _encounter_type encounter;




  typedef boost::shared_ptr< ::dgvmsg::Encounter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dgvmsg::Encounter_<ContainerAllocator> const> ConstPtr;

}; // struct Encounter_

typedef ::dgvmsg::Encounter_<std::allocator<void> > Encounter;

typedef boost::shared_ptr< ::dgvmsg::Encounter > EncounterPtr;
typedef boost::shared_ptr< ::dgvmsg::Encounter const> EncounterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dgvmsg::Encounter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dgvmsg::Encounter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dgvmsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'dgvmsg': ['/home/pc-robot/workspace/ubuntudev/03-controler/02-controller_232/src/dgvmsg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dgvmsg::Encounter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dgvmsg::Encounter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dgvmsg::Encounter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dgvmsg::Encounter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dgvmsg::Encounter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dgvmsg::Encounter_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dgvmsg::Encounter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "297ccc212aebf37b07c8d983c849a391";
  }

  static const char* value(const ::dgvmsg::Encounter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x297ccc212aebf37bULL;
  static const uint64_t static_value2 = 0x07c8d983c849a391ULL;
};

template<class ContainerAllocator>
struct DataType< ::dgvmsg::Encounter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dgvmsg/Encounter";
  }

  static const char* value(const ::dgvmsg::Encounter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dgvmsg::Encounter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message to hold data from an IMU (Inertial Measurement Unit)\n\
#\n\
# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n\
#\n\
# If the covariance of the measurement is known, it should be filled in (if all you know is the \n\
# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n\
# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n\
# data a covariance will have to be assumed or gotten from some other source\n\
#\n\
# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n\
# estimate), please set element 0 of the associated covariance matrix to -1\n\
# If you are interpreting this message, please check for a value of -1 in the first element of each \n\
# covariance matrix, and disregard the associated estimate.\n\
\n\
Header header\n\
\n\
int32 devadd\n\
time now\n\
uint32 encounter\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dgvmsg::Encounter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dgvmsg::Encounter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.devadd);
      stream.next(m.now);
      stream.next(m.encounter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encounter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dgvmsg::Encounter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dgvmsg::Encounter_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "devadd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.devadd);
    s << indent << "now: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.now);
    s << indent << "encounter: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encounter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DGVMSG_MESSAGE_ENCOUNTER_H
