// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExternSensor.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ExternSensor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ExternSensor_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExternSensor_reflection_ = NULL;
const ::google::protobuf::Descriptor* ExternSensor_Mode_Temp_humi_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExternSensor_Mode_Temp_humi_reflection_ = NULL;
const ::google::protobuf::Descriptor* ExternSensor_Mode_fan_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExternSensor_Mode_fan_reflection_ = NULL;
const ::google::protobuf::Descriptor* ExternSensor_Mode_PX24ES_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExternSensor_Mode_PX24ES_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ExternSensor_2eproto() {
  protobuf_AddDesc_ExternSensor_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ExternSensor.proto");
  GOOGLE_CHECK(file != NULL);
  ExternSensor_descriptor_ = file->message_type(0);
  static const int ExternSensor_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, temp_pt100_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, temp_humi_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, fan_msg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, io_infrared_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, io_collision_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, led_status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, px24es_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, online_),
  };
  ExternSensor_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ExternSensor_descriptor_,
      ExternSensor::default_instance_,
      ExternSensor_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ExternSensor));
  ExternSensor_Mode_Temp_humi_descriptor_ = ExternSensor_descriptor_->nested_type(0);
  static const int ExternSensor_Mode_Temp_humi_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_Temp_humi, interior_temp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_Temp_humi, interior_humi_),
  };
  ExternSensor_Mode_Temp_humi_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ExternSensor_Mode_Temp_humi_descriptor_,
      ExternSensor_Mode_Temp_humi::default_instance_,
      ExternSensor_Mode_Temp_humi_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_Temp_humi, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_Temp_humi, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ExternSensor_Mode_Temp_humi));
  ExternSensor_Mode_fan_descriptor_ = ExternSensor_descriptor_->nested_type(1);
  static const int ExternSensor_Mode_fan_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_fan, fan_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_fan, fan_mode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_fan, fan_status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_fan, vaule_open_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_fan, vaule_close_),
  };
  ExternSensor_Mode_fan_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ExternSensor_Mode_fan_descriptor_,
      ExternSensor_Mode_fan::default_instance_,
      ExternSensor_Mode_fan_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_fan, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_fan, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ExternSensor_Mode_fan));
  ExternSensor_Mode_PX24ES_descriptor_ = ExternSensor_descriptor_->nested_type(2);
  static const int ExternSensor_Mode_PX24ES_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_PX24ES, out1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_PX24ES, out2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_PX24ES, extraneouslight_out_),
  };
  ExternSensor_Mode_PX24ES_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ExternSensor_Mode_PX24ES_descriptor_,
      ExternSensor_Mode_PX24ES::default_instance_,
      ExternSensor_Mode_PX24ES_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_PX24ES, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExternSensor_Mode_PX24ES, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ExternSensor_Mode_PX24ES));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ExternSensor_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ExternSensor_descriptor_, &ExternSensor::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ExternSensor_Mode_Temp_humi_descriptor_, &ExternSensor_Mode_Temp_humi::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ExternSensor_Mode_fan_descriptor_, &ExternSensor_Mode_fan::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ExternSensor_Mode_PX24ES_descriptor_, &ExternSensor_Mode_PX24ES::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ExternSensor_2eproto() {
  delete ExternSensor::default_instance_;
  delete ExternSensor_reflection_;
  delete ExternSensor_Mode_Temp_humi::default_instance_;
  delete ExternSensor_Mode_Temp_humi_reflection_;
  delete ExternSensor_Mode_fan::default_instance_;
  delete ExternSensor_Mode_fan_reflection_;
  delete ExternSensor_Mode_PX24ES::default_instance_;
  delete ExternSensor_Mode_PX24ES_reflection_;
}

void protobuf_AddDesc_ExternSensor_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022ExternSensor.proto\"\351\003\n\014ExternSensor\022\022\n"
    "\nTemp_Pt100\030\001 \003(\005\022/\n\tTemp_humi\030\002 \003(\0132\034.E"
    "xternSensor.Mode_Temp_humi\022\'\n\007fan_msg\030\003 "
    "\003(\0132\026.ExternSensor.Mode_fan\022\023\n\013IO_Infrar"
    "ed\030\004 \003(\005\022\024\n\014IO_collision\030\005 \003(\005\022\022\n\nLED_st"
    "atus\030\006 \001(\t\022)\n\006PX24ES\030\007 \001(\0132\031.ExternSenso"
    "r.Mode_PX24ES\022\016\n\006online\030\010 \001(\005\032>\n\016Mode_Te"
    "mp_humi\022\025\n\rinterior_temp\030\001 \001(\005\022\025\n\rinteri"
    "or_humi\030\002 \001(\005\032i\n\010Mode_fan\022\016\n\006fan_ID\030\001 \001("
    "\005\022\020\n\010fan_Mode\030\002 \001(\005\022\022\n\nfan_status\030\003 \001(\005\022"
    "\022\n\nvaule_open\030\004 \001(\005\022\023\n\013vaule_close\030\005 \001(\005"
    "\032F\n\013Mode_PX24ES\022\014\n\004out1\030\001 \001(\005\022\014\n\004out2\030\002 "
    "\001(\005\022\033\n\023Extraneouslight_out\030\003 \001(\005", 512);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ExternSensor.proto", &protobuf_RegisterTypes);
  ExternSensor::default_instance_ = new ExternSensor();
  ExternSensor_Mode_Temp_humi::default_instance_ = new ExternSensor_Mode_Temp_humi();
  ExternSensor_Mode_fan::default_instance_ = new ExternSensor_Mode_fan();
  ExternSensor_Mode_PX24ES::default_instance_ = new ExternSensor_Mode_PX24ES();
  ExternSensor::default_instance_->InitAsDefaultInstance();
  ExternSensor_Mode_Temp_humi::default_instance_->InitAsDefaultInstance();
  ExternSensor_Mode_fan::default_instance_->InitAsDefaultInstance();
  ExternSensor_Mode_PX24ES::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ExternSensor_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ExternSensor_2eproto {
  StaticDescriptorInitializer_ExternSensor_2eproto() {
    protobuf_AddDesc_ExternSensor_2eproto();
  }
} static_descriptor_initializer_ExternSensor_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ExternSensor_Mode_Temp_humi::kInteriorTempFieldNumber;
const int ExternSensor_Mode_Temp_humi::kInteriorHumiFieldNumber;
#endif  // !_MSC_VER

ExternSensor_Mode_Temp_humi::ExternSensor_Mode_Temp_humi()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ExternSensor_Mode_Temp_humi::InitAsDefaultInstance() {
}

ExternSensor_Mode_Temp_humi::ExternSensor_Mode_Temp_humi(const ExternSensor_Mode_Temp_humi& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ExternSensor_Mode_Temp_humi::SharedCtor() {
  _cached_size_ = 0;
  interior_temp_ = 0;
  interior_humi_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ExternSensor_Mode_Temp_humi::~ExternSensor_Mode_Temp_humi() {
  SharedDtor();
}

void ExternSensor_Mode_Temp_humi::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ExternSensor_Mode_Temp_humi::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExternSensor_Mode_Temp_humi::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExternSensor_Mode_Temp_humi_descriptor_;
}

const ExternSensor_Mode_Temp_humi& ExternSensor_Mode_Temp_humi::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ExternSensor_2eproto();
  return *default_instance_;
}

ExternSensor_Mode_Temp_humi* ExternSensor_Mode_Temp_humi::default_instance_ = NULL;

ExternSensor_Mode_Temp_humi* ExternSensor_Mode_Temp_humi::New() const {
  return new ExternSensor_Mode_Temp_humi;
}

void ExternSensor_Mode_Temp_humi::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    interior_temp_ = 0;
    interior_humi_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ExternSensor_Mode_Temp_humi::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 interior_temp = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &interior_temp_)));
          set_has_interior_temp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_interior_humi;
        break;
      }

      // optional int32 interior_humi = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_interior_humi:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &interior_humi_)));
          set_has_interior_humi();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ExternSensor_Mode_Temp_humi::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 interior_temp = 1;
  if (has_interior_temp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->interior_temp(), output);
  }

  // optional int32 interior_humi = 2;
  if (has_interior_humi()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->interior_humi(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ExternSensor_Mode_Temp_humi::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 interior_temp = 1;
  if (has_interior_temp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->interior_temp(), target);
  }

  // optional int32 interior_humi = 2;
  if (has_interior_humi()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->interior_humi(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ExternSensor_Mode_Temp_humi::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 interior_temp = 1;
    if (has_interior_temp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->interior_temp());
    }

    // optional int32 interior_humi = 2;
    if (has_interior_humi()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->interior_humi());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExternSensor_Mode_Temp_humi::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ExternSensor_Mode_Temp_humi* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ExternSensor_Mode_Temp_humi*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ExternSensor_Mode_Temp_humi::MergeFrom(const ExternSensor_Mode_Temp_humi& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_interior_temp()) {
      set_interior_temp(from.interior_temp());
    }
    if (from.has_interior_humi()) {
      set_interior_humi(from.interior_humi());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ExternSensor_Mode_Temp_humi::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExternSensor_Mode_Temp_humi::CopyFrom(const ExternSensor_Mode_Temp_humi& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExternSensor_Mode_Temp_humi::IsInitialized() const {

  return true;
}

void ExternSensor_Mode_Temp_humi::Swap(ExternSensor_Mode_Temp_humi* other) {
  if (other != this) {
    std::swap(interior_temp_, other->interior_temp_);
    std::swap(interior_humi_, other->interior_humi_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ExternSensor_Mode_Temp_humi::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExternSensor_Mode_Temp_humi_descriptor_;
  metadata.reflection = ExternSensor_Mode_Temp_humi_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ExternSensor_Mode_fan::kFanIDFieldNumber;
const int ExternSensor_Mode_fan::kFanModeFieldNumber;
const int ExternSensor_Mode_fan::kFanStatusFieldNumber;
const int ExternSensor_Mode_fan::kVauleOpenFieldNumber;
const int ExternSensor_Mode_fan::kVauleCloseFieldNumber;
#endif  // !_MSC_VER

ExternSensor_Mode_fan::ExternSensor_Mode_fan()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ExternSensor_Mode_fan::InitAsDefaultInstance() {
}

ExternSensor_Mode_fan::ExternSensor_Mode_fan(const ExternSensor_Mode_fan& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ExternSensor_Mode_fan::SharedCtor() {
  _cached_size_ = 0;
  fan_id_ = 0;
  fan_mode_ = 0;
  fan_status_ = 0;
  vaule_open_ = 0;
  vaule_close_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ExternSensor_Mode_fan::~ExternSensor_Mode_fan() {
  SharedDtor();
}

void ExternSensor_Mode_fan::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ExternSensor_Mode_fan::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExternSensor_Mode_fan::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExternSensor_Mode_fan_descriptor_;
}

const ExternSensor_Mode_fan& ExternSensor_Mode_fan::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ExternSensor_2eproto();
  return *default_instance_;
}

ExternSensor_Mode_fan* ExternSensor_Mode_fan::default_instance_ = NULL;

ExternSensor_Mode_fan* ExternSensor_Mode_fan::New() const {
  return new ExternSensor_Mode_fan;
}

void ExternSensor_Mode_fan::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    fan_id_ = 0;
    fan_mode_ = 0;
    fan_status_ = 0;
    vaule_open_ = 0;
    vaule_close_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ExternSensor_Mode_fan::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 fan_ID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fan_id_)));
          set_has_fan_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_fan_Mode;
        break;
      }

      // optional int32 fan_Mode = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_fan_Mode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fan_mode_)));
          set_has_fan_mode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_fan_status;
        break;
      }

      // optional int32 fan_status = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_fan_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fan_status_)));
          set_has_fan_status();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_vaule_open;
        break;
      }

      // optional int32 vaule_open = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vaule_open:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &vaule_open_)));
          set_has_vaule_open();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_vaule_close;
        break;
      }

      // optional int32 vaule_close = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vaule_close:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &vaule_close_)));
          set_has_vaule_close();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ExternSensor_Mode_fan::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 fan_ID = 1;
  if (has_fan_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->fan_id(), output);
  }

  // optional int32 fan_Mode = 2;
  if (has_fan_mode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->fan_mode(), output);
  }

  // optional int32 fan_status = 3;
  if (has_fan_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->fan_status(), output);
  }

  // optional int32 vaule_open = 4;
  if (has_vaule_open()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->vaule_open(), output);
  }

  // optional int32 vaule_close = 5;
  if (has_vaule_close()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->vaule_close(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ExternSensor_Mode_fan::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 fan_ID = 1;
  if (has_fan_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->fan_id(), target);
  }

  // optional int32 fan_Mode = 2;
  if (has_fan_mode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->fan_mode(), target);
  }

  // optional int32 fan_status = 3;
  if (has_fan_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->fan_status(), target);
  }

  // optional int32 vaule_open = 4;
  if (has_vaule_open()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->vaule_open(), target);
  }

  // optional int32 vaule_close = 5;
  if (has_vaule_close()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->vaule_close(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ExternSensor_Mode_fan::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 fan_ID = 1;
    if (has_fan_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fan_id());
    }

    // optional int32 fan_Mode = 2;
    if (has_fan_mode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fan_mode());
    }

    // optional int32 fan_status = 3;
    if (has_fan_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fan_status());
    }

    // optional int32 vaule_open = 4;
    if (has_vaule_open()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->vaule_open());
    }

    // optional int32 vaule_close = 5;
    if (has_vaule_close()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->vaule_close());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExternSensor_Mode_fan::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ExternSensor_Mode_fan* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ExternSensor_Mode_fan*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ExternSensor_Mode_fan::MergeFrom(const ExternSensor_Mode_fan& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_fan_id()) {
      set_fan_id(from.fan_id());
    }
    if (from.has_fan_mode()) {
      set_fan_mode(from.fan_mode());
    }
    if (from.has_fan_status()) {
      set_fan_status(from.fan_status());
    }
    if (from.has_vaule_open()) {
      set_vaule_open(from.vaule_open());
    }
    if (from.has_vaule_close()) {
      set_vaule_close(from.vaule_close());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ExternSensor_Mode_fan::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExternSensor_Mode_fan::CopyFrom(const ExternSensor_Mode_fan& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExternSensor_Mode_fan::IsInitialized() const {

  return true;
}

void ExternSensor_Mode_fan::Swap(ExternSensor_Mode_fan* other) {
  if (other != this) {
    std::swap(fan_id_, other->fan_id_);
    std::swap(fan_mode_, other->fan_mode_);
    std::swap(fan_status_, other->fan_status_);
    std::swap(vaule_open_, other->vaule_open_);
    std::swap(vaule_close_, other->vaule_close_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ExternSensor_Mode_fan::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExternSensor_Mode_fan_descriptor_;
  metadata.reflection = ExternSensor_Mode_fan_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ExternSensor_Mode_PX24ES::kOut1FieldNumber;
const int ExternSensor_Mode_PX24ES::kOut2FieldNumber;
const int ExternSensor_Mode_PX24ES::kExtraneouslightOutFieldNumber;
#endif  // !_MSC_VER

ExternSensor_Mode_PX24ES::ExternSensor_Mode_PX24ES()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ExternSensor_Mode_PX24ES::InitAsDefaultInstance() {
}

ExternSensor_Mode_PX24ES::ExternSensor_Mode_PX24ES(const ExternSensor_Mode_PX24ES& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ExternSensor_Mode_PX24ES::SharedCtor() {
  _cached_size_ = 0;
  out1_ = 0;
  out2_ = 0;
  extraneouslight_out_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ExternSensor_Mode_PX24ES::~ExternSensor_Mode_PX24ES() {
  SharedDtor();
}

void ExternSensor_Mode_PX24ES::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ExternSensor_Mode_PX24ES::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExternSensor_Mode_PX24ES::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExternSensor_Mode_PX24ES_descriptor_;
}

const ExternSensor_Mode_PX24ES& ExternSensor_Mode_PX24ES::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ExternSensor_2eproto();
  return *default_instance_;
}

ExternSensor_Mode_PX24ES* ExternSensor_Mode_PX24ES::default_instance_ = NULL;

ExternSensor_Mode_PX24ES* ExternSensor_Mode_PX24ES::New() const {
  return new ExternSensor_Mode_PX24ES;
}

void ExternSensor_Mode_PX24ES::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    out1_ = 0;
    out2_ = 0;
    extraneouslight_out_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ExternSensor_Mode_PX24ES::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 out1 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &out1_)));
          set_has_out1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_out2;
        break;
      }

      // optional int32 out2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_out2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &out2_)));
          set_has_out2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_Extraneouslight_out;
        break;
      }

      // optional int32 Extraneouslight_out = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Extraneouslight_out:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &extraneouslight_out_)));
          set_has_extraneouslight_out();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ExternSensor_Mode_PX24ES::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 out1 = 1;
  if (has_out1()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->out1(), output);
  }

  // optional int32 out2 = 2;
  if (has_out2()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->out2(), output);
  }

  // optional int32 Extraneouslight_out = 3;
  if (has_extraneouslight_out()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->extraneouslight_out(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ExternSensor_Mode_PX24ES::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 out1 = 1;
  if (has_out1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->out1(), target);
  }

  // optional int32 out2 = 2;
  if (has_out2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->out2(), target);
  }

  // optional int32 Extraneouslight_out = 3;
  if (has_extraneouslight_out()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->extraneouslight_out(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ExternSensor_Mode_PX24ES::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 out1 = 1;
    if (has_out1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->out1());
    }

    // optional int32 out2 = 2;
    if (has_out2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->out2());
    }

    // optional int32 Extraneouslight_out = 3;
    if (has_extraneouslight_out()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->extraneouslight_out());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExternSensor_Mode_PX24ES::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ExternSensor_Mode_PX24ES* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ExternSensor_Mode_PX24ES*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ExternSensor_Mode_PX24ES::MergeFrom(const ExternSensor_Mode_PX24ES& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_out1()) {
      set_out1(from.out1());
    }
    if (from.has_out2()) {
      set_out2(from.out2());
    }
    if (from.has_extraneouslight_out()) {
      set_extraneouslight_out(from.extraneouslight_out());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ExternSensor_Mode_PX24ES::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExternSensor_Mode_PX24ES::CopyFrom(const ExternSensor_Mode_PX24ES& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExternSensor_Mode_PX24ES::IsInitialized() const {

  return true;
}

void ExternSensor_Mode_PX24ES::Swap(ExternSensor_Mode_PX24ES* other) {
  if (other != this) {
    std::swap(out1_, other->out1_);
    std::swap(out2_, other->out2_);
    std::swap(extraneouslight_out_, other->extraneouslight_out_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ExternSensor_Mode_PX24ES::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExternSensor_Mode_PX24ES_descriptor_;
  metadata.reflection = ExternSensor_Mode_PX24ES_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int ExternSensor::kTempPt100FieldNumber;
const int ExternSensor::kTempHumiFieldNumber;
const int ExternSensor::kFanMsgFieldNumber;
const int ExternSensor::kIOInfraredFieldNumber;
const int ExternSensor::kIOCollisionFieldNumber;
const int ExternSensor::kLEDStatusFieldNumber;
const int ExternSensor::kPX24ESFieldNumber;
const int ExternSensor::kOnlineFieldNumber;
#endif  // !_MSC_VER

ExternSensor::ExternSensor()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ExternSensor::InitAsDefaultInstance() {
  px24es_ = const_cast< ::ExternSensor_Mode_PX24ES*>(&::ExternSensor_Mode_PX24ES::default_instance());
}

ExternSensor::ExternSensor(const ExternSensor& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ExternSensor::SharedCtor() {
  _cached_size_ = 0;
  led_status_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  px24es_ = NULL;
  online_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ExternSensor::~ExternSensor() {
  SharedDtor();
}

void ExternSensor::SharedDtor() {
  if (led_status_ != &::google::protobuf::internal::kEmptyString) {
    delete led_status_;
  }
  if (this != default_instance_) {
    delete px24es_;
  }
}

void ExternSensor::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExternSensor::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExternSensor_descriptor_;
}

const ExternSensor& ExternSensor::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ExternSensor_2eproto();
  return *default_instance_;
}

ExternSensor* ExternSensor::default_instance_ = NULL;

ExternSensor* ExternSensor::New() const {
  return new ExternSensor;
}

void ExternSensor::Clear() {
  if (_has_bits_[5 / 32] & (0xffu << (5 % 32))) {
    if (has_led_status()) {
      if (led_status_ != &::google::protobuf::internal::kEmptyString) {
        led_status_->clear();
      }
    }
    if (has_px24es()) {
      if (px24es_ != NULL) px24es_->::ExternSensor_Mode_PX24ES::Clear();
    }
    online_ = 0;
  }
  temp_pt100_.Clear();
  temp_humi_.Clear();
  fan_msg_.Clear();
  io_infrared_.Clear();
  io_collision_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ExternSensor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 Temp_Pt100 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Temp_Pt100:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_temp_pt100())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_temp_pt100())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_Temp_Pt100;
        if (input->ExpectTag(18)) goto parse_Temp_humi;
        break;
      }

      // repeated .ExternSensor.Mode_Temp_humi Temp_humi = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Temp_humi:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_temp_humi()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_Temp_humi;
        if (input->ExpectTag(26)) goto parse_fan_msg;
        break;
      }

      // repeated .ExternSensor.Mode_fan fan_msg = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_fan_msg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_fan_msg()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_fan_msg;
        if (input->ExpectTag(32)) goto parse_IO_Infrared;
        break;
      }

      // repeated int32 IO_Infrared = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_IO_Infrared:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_io_infrared())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_io_infrared())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_IO_Infrared;
        if (input->ExpectTag(40)) goto parse_IO_collision;
        break;
      }

      // repeated int32 IO_collision = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_IO_collision:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 40, input, this->mutable_io_collision())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_io_collision())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_IO_collision;
        if (input->ExpectTag(50)) goto parse_LED_status;
        break;
      }

      // optional string LED_status = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_LED_status:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_led_status()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->led_status().data(), this->led_status().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_PX24ES;
        break;
      }

      // optional .ExternSensor.Mode_PX24ES PX24ES = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_PX24ES:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_px24es()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_online;
        break;
      }

      // optional int32 online = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_online:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &online_)));
          set_has_online();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ExternSensor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 Temp_Pt100 = 1;
  for (int i = 0; i < this->temp_pt100_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->temp_pt100(i), output);
  }

  // repeated .ExternSensor.Mode_Temp_humi Temp_humi = 2;
  for (int i = 0; i < this->temp_humi_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->temp_humi(i), output);
  }

  // repeated .ExternSensor.Mode_fan fan_msg = 3;
  for (int i = 0; i < this->fan_msg_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->fan_msg(i), output);
  }

  // repeated int32 IO_Infrared = 4;
  for (int i = 0; i < this->io_infrared_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->io_infrared(i), output);
  }

  // repeated int32 IO_collision = 5;
  for (int i = 0; i < this->io_collision_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      5, this->io_collision(i), output);
  }

  // optional string LED_status = 6;
  if (has_led_status()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->led_status().data(), this->led_status().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->led_status(), output);
  }

  // optional .ExternSensor.Mode_PX24ES PX24ES = 7;
  if (has_px24es()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->px24es(), output);
  }

  // optional int32 online = 8;
  if (has_online()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->online(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ExternSensor::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 Temp_Pt100 = 1;
  for (int i = 0; i < this->temp_pt100_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->temp_pt100(i), target);
  }

  // repeated .ExternSensor.Mode_Temp_humi Temp_humi = 2;
  for (int i = 0; i < this->temp_humi_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->temp_humi(i), target);
  }

  // repeated .ExternSensor.Mode_fan fan_msg = 3;
  for (int i = 0; i < this->fan_msg_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->fan_msg(i), target);
  }

  // repeated int32 IO_Infrared = 4;
  for (int i = 0; i < this->io_infrared_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(4, this->io_infrared(i), target);
  }

  // repeated int32 IO_collision = 5;
  for (int i = 0; i < this->io_collision_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(5, this->io_collision(i), target);
  }

  // optional string LED_status = 6;
  if (has_led_status()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->led_status().data(), this->led_status().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->led_status(), target);
  }

  // optional .ExternSensor.Mode_PX24ES PX24ES = 7;
  if (has_px24es()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->px24es(), target);
  }

  // optional int32 online = 8;
  if (has_online()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->online(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ExternSensor::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[5 / 32] & (0xffu << (5 % 32))) {
    // optional string LED_status = 6;
    if (has_led_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->led_status());
    }

    // optional .ExternSensor.Mode_PX24ES PX24ES = 7;
    if (has_px24es()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->px24es());
    }

    // optional int32 online = 8;
    if (has_online()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->online());
    }

  }
  // repeated int32 Temp_Pt100 = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->temp_pt100_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->temp_pt100(i));
    }
    total_size += 1 * this->temp_pt100_size() + data_size;
  }

  // repeated .ExternSensor.Mode_Temp_humi Temp_humi = 2;
  total_size += 1 * this->temp_humi_size();
  for (int i = 0; i < this->temp_humi_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->temp_humi(i));
  }

  // repeated .ExternSensor.Mode_fan fan_msg = 3;
  total_size += 1 * this->fan_msg_size();
  for (int i = 0; i < this->fan_msg_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->fan_msg(i));
  }

  // repeated int32 IO_Infrared = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->io_infrared_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->io_infrared(i));
    }
    total_size += 1 * this->io_infrared_size() + data_size;
  }

  // repeated int32 IO_collision = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->io_collision_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->io_collision(i));
    }
    total_size += 1 * this->io_collision_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExternSensor::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ExternSensor* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ExternSensor*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ExternSensor::MergeFrom(const ExternSensor& from) {
  GOOGLE_CHECK_NE(&from, this);
  temp_pt100_.MergeFrom(from.temp_pt100_);
  temp_humi_.MergeFrom(from.temp_humi_);
  fan_msg_.MergeFrom(from.fan_msg_);
  io_infrared_.MergeFrom(from.io_infrared_);
  io_collision_.MergeFrom(from.io_collision_);
  if (from._has_bits_[5 / 32] & (0xffu << (5 % 32))) {
    if (from.has_led_status()) {
      set_led_status(from.led_status());
    }
    if (from.has_px24es()) {
      mutable_px24es()->::ExternSensor_Mode_PX24ES::MergeFrom(from.px24es());
    }
    if (from.has_online()) {
      set_online(from.online());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ExternSensor::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExternSensor::CopyFrom(const ExternSensor& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExternSensor::IsInitialized() const {

  return true;
}

void ExternSensor::Swap(ExternSensor* other) {
  if (other != this) {
    temp_pt100_.Swap(&other->temp_pt100_);
    temp_humi_.Swap(&other->temp_humi_);
    fan_msg_.Swap(&other->fan_msg_);
    io_infrared_.Swap(&other->io_infrared_);
    io_collision_.Swap(&other->io_collision_);
    std::swap(led_status_, other->led_status_);
    std::swap(px24es_, other->px24es_);
    std::swap(online_, other->online_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ExternSensor::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExternSensor_descriptor_;
  metadata.reflection = ExternSensor_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
