/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ParamConfig.pb-c.h"
void   param_config__config__mode__driver__init
                     (ParamConfig__ConfigModeDriver         *message)
{
  static ParamConfig__ConfigModeDriver init_value = PARAM_CONFIG__CONFIG__MODE__DRIVER__INIT;
  *message = init_value;
}
void   param_config__config__error__mode__init
                     (ParamConfig__ConfigErrorMode         *message)
{
  static ParamConfig__ConfigErrorMode init_value = PARAM_CONFIG__CONFIG__ERROR__MODE__INIT;
  *message = init_value;
}
void   param_config__config__alarm__mode__init
                     (ParamConfig__ConfigAlarmMode         *message)
{
  static ParamConfig__ConfigAlarmMode init_value = PARAM_CONFIG__CONFIG__ALARM__MODE__INIT;
  *message = init_value;
}
void   param_config__init
                     (ParamConfig         *message)
{
  static ParamConfig init_value = PARAM_CONFIG__INIT;
  *message = init_value;
}
size_t param_config__get_packed_size
                     (const ParamConfig *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &param_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t param_config__pack
                     (const ParamConfig *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &param_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t param_config__pack_to_buffer
                     (const ParamConfig *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &param_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParamConfig *
       param_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParamConfig *)
     protobuf_c_message_unpack (&param_config__descriptor,
                                allocator, len, data);
}
void   param_config__free_unpacked
                     (ParamConfig *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &param_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor param_config__config__mode__driver__field_descriptors[10] =
{
  {
    "autorun_speed",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_autorun_speed),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, autorun_speed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autorun_angel",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_autorun_angel),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, autorun_angel),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_speed",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_remote_speed),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, remote_speed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_angel",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_remote_angel),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, remote_angel),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_AcceVelocity",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_remote_accevelocity),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, remote_accevelocity),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ReductionRatiol",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_reductionratiol),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, reductionratiol),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "WheelSsize",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_wheelssize),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, wheelssize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RWheelSsize",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_rwheelssize),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, rwheelssize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LWheelSsize",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_lwheelssize),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, lwheelssize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EcounterRpm",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, has_ecounterrpm),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigModeDriver, ecounterrpm),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned param_config__config__mode__driver__field_indices_by_name[] = {
  9,   /* field[9] = EcounterRpm */
  8,   /* field[8] = LWheelSsize */
  7,   /* field[7] = RWheelSsize */
  5,   /* field[5] = ReductionRatiol */
  6,   /* field[6] = WheelSsize */
  1,   /* field[1] = autorun_angel */
  0,   /* field[0] = autorun_speed */
  4,   /* field[4] = remote_AcceVelocity */
  3,   /* field[3] = remote_angel */
  2,   /* field[2] = remote_speed */
};
static const ProtobufCIntRange param_config__config__mode__driver__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor param_config__config__mode__driver__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ParamConfig.Config_Mode_Driver",
  "ConfigModeDriver",
  "ParamConfig__ConfigModeDriver",
  "",
  sizeof(ParamConfig__ConfigModeDriver),
  10,
  param_config__config__mode__driver__field_descriptors,
  param_config__config__mode__driver__field_indices_by_name,
  1,  param_config__config__mode__driver__number_ranges,
  (ProtobufCMessageInit) param_config__config__mode__driver__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor param_config__config__error__mode__field_descriptors[16] =
{
  {
    "CarLeftFDriverError_Ischeck",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_carleftfdrivererror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, carleftfdrivererror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CarRightFDriverError_Ischeck",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_carrightfdrivererror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, carrightfdrivererror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CarLeftBDriverError_Ischeck",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_carleftbdrivererror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, carleftbdrivererror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CarRightBDriverError_Ischeck",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_carrightbdrivererror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, carrightbdrivererror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LeftFDriverComError_Ischeck",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_leftfdrivercomerror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, leftfdrivercomerror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RightFDriverComError_Ischeck",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_rightfdrivercomerror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, rightfdrivercomerror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LeftBDriverComError_Ischeck",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_leftbdrivercomerror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, leftbdrivercomerror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RightBDriverComError_Ischeck",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_rightbdrivercomerror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, rightbdrivercomerror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ExternComDevError_Ischeck",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_externcomdeverror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, externcomdeverror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BMSSysError_Ischeck",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_bmssyserror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, bmssyserror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ObstacleStopError_Ischeck",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_obstaclestoperror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, obstaclestoperror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CashSwitchStopError_Ischeck",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_cashswitchstoperror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, cashswitchstoperror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CurrentOverloadError_Ischeck",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_currentoverloaderror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, currentoverloaderror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xrs2015_driverNodeOFF_Ischeck",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_xrs2015_drivernodeoff_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, xrs2015_drivernodeoff_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BObstacleStopError_Ischeck",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_bobstaclestoperror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, bobstaclestoperror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DropStopError_Ischeck",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, has_dropstoperror_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigErrorMode, dropstoperror_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned param_config__config__error__mode__field_indices_by_name[] = {
  9,   /* field[9] = BMSSysError_Ischeck */
  14,   /* field[14] = BObstacleStopError_Ischeck */
  2,   /* field[2] = CarLeftBDriverError_Ischeck */
  0,   /* field[0] = CarLeftFDriverError_Ischeck */
  3,   /* field[3] = CarRightBDriverError_Ischeck */
  1,   /* field[1] = CarRightFDriverError_Ischeck */
  11,   /* field[11] = CashSwitchStopError_Ischeck */
  12,   /* field[12] = CurrentOverloadError_Ischeck */
  15,   /* field[15] = DropStopError_Ischeck */
  8,   /* field[8] = ExternComDevError_Ischeck */
  6,   /* field[6] = LeftBDriverComError_Ischeck */
  4,   /* field[4] = LeftFDriverComError_Ischeck */
  10,   /* field[10] = ObstacleStopError_Ischeck */
  7,   /* field[7] = RightBDriverComError_Ischeck */
  5,   /* field[5] = RightFDriverComError_Ischeck */
  13,   /* field[13] = xrs2015_driverNodeOFF_Ischeck */
};
static const ProtobufCIntRange param_config__config__error__mode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor param_config__config__error__mode__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ParamConfig.Config_Error_Mode",
  "ConfigErrorMode",
  "ParamConfig__ConfigErrorMode",
  "",
  sizeof(ParamConfig__ConfigErrorMode),
  16,
  param_config__config__error__mode__field_descriptors,
  param_config__config__error__mode__field_indices_by_name,
  1,  param_config__config__error__mode__number_ranges,
  (ProtobufCMessageInit) param_config__config__error__mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor param_config__config__alarm__mode__field_descriptors[9] =
{
  {
    "CtrolBoxHighTemAlarm_Ischeck",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_ctrolboxhightemalarm_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, ctrolboxhightemalarm_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CtrolBoxFrozenTemAlarm_Ischeck",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_ctrolboxfrozentemalarm_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, ctrolboxfrozentemalarm_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BMSModComLostAlarm_Ischeck",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_bmsmodcomlostalarm_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, bmsmodcomlostalarm_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Emergency_Status_stop_Ischeck",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_emergency_status_stop_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, emergency_status_stop_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EcanExternSnsorNdeOFF_Ischeck",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_ecanexternsnsorndeoff_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, ecanexternsnsorndeoff_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ZmqTransNodeOFF_Ischeck",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_zmqtransnodeoff_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, zmqtransnodeoff_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "JoyTestNodeOFF_Ischeck",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_joytestnodeoff_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, joytestnodeoff_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ph3ReadNodeOFF_Ischeck",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_ph3readnodeoff_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, ph3readnodeoff_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ph3ReadComLost_Ischeck",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, has_ph3readcomlost_ischeck),
    PROTOBUF_C_OFFSETOF(ParamConfig__ConfigAlarmMode, ph3readcomlost_ischeck),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned param_config__config__alarm__mode__field_indices_by_name[] = {
  2,   /* field[2] = BMSModComLostAlarm_Ischeck */
  1,   /* field[1] = CtrolBoxFrozenTemAlarm_Ischeck */
  0,   /* field[0] = CtrolBoxHighTemAlarm_Ischeck */
  4,   /* field[4] = EcanExternSnsorNdeOFF_Ischeck */
  3,   /* field[3] = Emergency_Status_stop_Ischeck */
  6,   /* field[6] = JoyTestNodeOFF_Ischeck */
  8,   /* field[8] = Ph3ReadComLost_Ischeck */
  7,   /* field[7] = Ph3ReadNodeOFF_Ischeck */
  5,   /* field[5] = ZmqTransNodeOFF_Ischeck */
};
static const ProtobufCIntRange param_config__config__alarm__mode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor param_config__config__alarm__mode__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ParamConfig.Config_Alarm_Mode",
  "ConfigAlarmMode",
  "ParamConfig__ConfigAlarmMode",
  "",
  sizeof(ParamConfig__ConfigAlarmMode),
  9,
  param_config__config__alarm__mode__field_descriptors,
  param_config__config__alarm__mode__field_indices_by_name,
  1,  param_config__config__alarm__mode__number_ranges,
  (ProtobufCMessageInit) param_config__config__alarm__mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor param_config__field_descriptors[4] =
{
  {
    "Config_Driver_Msg",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ParamConfig, config_driver_msg),
    &param_config__config__mode__driver__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Config_Error_Msg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ParamConfig, config_error_msg),
    &param_config__config__error__mode__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Config_Alarm_Msg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ParamConfig, config_alarm_msg),
    &param_config__config__alarm__mode__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Config_extern_Msg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ParamConfig, config_extern_msg),
    &extern_sensor_config__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned param_config__field_indices_by_name[] = {
  2,   /* field[2] = Config_Alarm_Msg */
  0,   /* field[0] = Config_Driver_Msg */
  1,   /* field[1] = Config_Error_Msg */
  3,   /* field[3] = Config_extern_Msg */
};
static const ProtobufCIntRange param_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor param_config__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ParamConfig",
  "ParamConfig",
  "ParamConfig",
  "",
  sizeof(ParamConfig),
  4,
  param_config__field_descriptors,
  param_config__field_indices_by_name,
  1,  param_config__number_ranges,
  (ProtobufCMessageInit) param_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
