/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: BmsModeConfig.proto */

#ifndef PROTOBUF_C_BmsModeConfig_2eproto__INCLUDED
#define PROTOBUF_C_BmsModeConfig_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _BmsModeConfig BmsModeConfig;
typedef struct _BmsModeConfig__SOCConfig BmsModeConfig__SOCConfig;
typedef struct _BmsModeConfig__FanConfig BmsModeConfig__FanConfig;
typedef struct _BmsModeConfig__NomalConfig BmsModeConfig__NomalConfig;


/* --- enums --- */


/* --- messages --- */

struct  _BmsModeConfig__SOCConfig
{
  ProtobufCMessage base;
  protobuf_c_boolean has_full_soc;
  int32_t full_soc;
  protobuf_c_boolean has_current_soc;
  int32_t current_soc;
};
#define BMS_MODE_CONFIG__SOC__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bms_mode_config__soc__config__descriptor) \
    , 0,0, 0,0 }


struct  _BmsModeConfig__FanConfig
{
  ProtobufCMessage base;
  protobuf_c_boolean has_open;
  int32_t open;
  protobuf_c_boolean has_close;
  int32_t close;
};
#define BMS_MODE_CONFIG__FAN__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bms_mode_config__fan__config__descriptor) \
    , 0,0, 0,0 }


struct  _BmsModeConfig__NomalConfig
{
  ProtobufCMessage base;
  /*
   *充电开启关闭  1 开启 0 关闭
   */
  protobuf_c_boolean has_ctrl_charge;
  int32_t ctrl_charge;
  /*
   *风扇模式控制  1 auto 0 关闭
   */
  protobuf_c_boolean has_ctrl_fan;
  int32_t ctrl_fan;
  /*
   *系统复位控制  1 出发一次重上电 0 正常供电
   */
  protobuf_c_boolean has_ctrl_reset;
  int32_t ctrl_reset;
  /*
   *报警释放  1 清除所有故障位 0 关闭
   */
  protobuf_c_boolean has_alarm_release;
  int32_t alarm_release;
  /*
   *动力电控制  1 接通 0 关闭
   */
  protobuf_c_boolean has_ctrl_motor_power;
  int32_t ctrl_motor_power;
};
#define BMS_MODE_CONFIG__NOMAL__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bms_mode_config__nomal__config__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0 }


struct  _BmsModeConfig
{
  ProtobufCMessage base;
  /*
   *常规控制
   */
  BmsModeConfig__NomalConfig *nomal;
  /*
   *容量配置
   */
  BmsModeConfig__SOCConfig *soc;
  /*
   *风扇配置
   */
  BmsModeConfig__FanConfig *fan;
};
#define BMS_MODE_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bms_mode_config__descriptor) \
    , NULL, NULL, NULL }


/* BmsModeConfig__SOCConfig methods */
void   bms_mode_config__soc__config__init
                     (BmsModeConfig__SOCConfig         *message);
/* BmsModeConfig__FanConfig methods */
void   bms_mode_config__fan__config__init
                     (BmsModeConfig__FanConfig         *message);
/* BmsModeConfig__NomalConfig methods */
void   bms_mode_config__nomal__config__init
                     (BmsModeConfig__NomalConfig         *message);
/* BmsModeConfig methods */
void   bms_mode_config__init
                     (BmsModeConfig         *message);
size_t bms_mode_config__get_packed_size
                     (const BmsModeConfig   *message);
size_t bms_mode_config__pack
                     (const BmsModeConfig   *message,
                      uint8_t             *out);
size_t bms_mode_config__pack_to_buffer
                     (const BmsModeConfig   *message,
                      ProtobufCBuffer     *buffer);
BmsModeConfig *
       bms_mode_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bms_mode_config__free_unpacked
                     (BmsModeConfig *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BmsModeConfig__SOCConfig_Closure)
                 (const BmsModeConfig__SOCConfig *message,
                  void *closure_data);
typedef void (*BmsModeConfig__FanConfig_Closure)
                 (const BmsModeConfig__FanConfig *message,
                  void *closure_data);
typedef void (*BmsModeConfig__NomalConfig_Closure)
                 (const BmsModeConfig__NomalConfig *message,
                  void *closure_data);
typedef void (*BmsModeConfig_Closure)
                 (const BmsModeConfig *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bms_mode_config__descriptor;
extern const ProtobufCMessageDescriptor bms_mode_config__soc__config__descriptor;
extern const ProtobufCMessageDescriptor bms_mode_config__fan__config__descriptor;
extern const ProtobufCMessageDescriptor bms_mode_config__nomal__config__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_BmsModeConfig_2eproto__INCLUDED */
