/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: WeatherMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "WeatherMessage.pb-c.h"
void   weather_message__gps__init
                     (WeatherMessage__GPS         *message)
{
  static WeatherMessage__GPS init_value = WEATHER_MESSAGE__GPS__INIT;
  *message = init_value;
}
void   weather_message__date_time__init
                     (WeatherMessage__DateTime         *message)
{
  static WeatherMessage__DateTime init_value = WEATHER_MESSAGE__DATE_TIME__INIT;
  *message = init_value;
}
void   weather_message__init
                     (WeatherMessage         *message)
{
  static WeatherMessage init_value = WEATHER_MESSAGE__INIT;
  *message = init_value;
}
size_t weather_message__get_packed_size
                     (const WeatherMessage *message)
{
  assert(message->base.descriptor == &weather_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t weather_message__pack
                     (const WeatherMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &weather_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t weather_message__pack_to_buffer
                     (const WeatherMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &weather_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WeatherMessage *
       weather_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WeatherMessage *)
     protobuf_c_message_unpack (&weather_message__descriptor,
                                allocator, len, data);
}
void   weather_message__free_unpacked
                     (WeatherMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &weather_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor weather_message__gps__field_descriptors[3] =
{
  {
    "La",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage__GPS, has_la),
    offsetof(WeatherMessage__GPS, la),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Lo",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage__GPS, has_lo),
    offsetof(WeatherMessage__GPS, lo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GPSTime",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(WeatherMessage__GPS, has_gpstime),
    offsetof(WeatherMessage__GPS, gpstime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather_message__gps__field_indices_by_name[] = {
  2,   /* field[2] = GPSTime */
  0,   /* field[0] = La */
  1,   /* field[1] = Lo */
};
static const ProtobufCIntRange weather_message__gps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor weather_message__gps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WeatherMessage.GPS",
  "GPS",
  "WeatherMessage__GPS",
  "",
  sizeof(WeatherMessage__GPS),
  3,
  weather_message__gps__field_descriptors,
  weather_message__gps__field_indices_by_name,
  1,  weather_message__gps__number_ranges,
  (ProtobufCMessageInit) weather_message__gps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor weather_message__date_time__field_descriptors[6] =
{
  {
    "Year",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WeatherMessage__DateTime, has_year),
    offsetof(WeatherMessage__DateTime, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Month",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WeatherMessage__DateTime, has_month),
    offsetof(WeatherMessage__DateTime, month),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Day",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WeatherMessage__DateTime, has_day),
    offsetof(WeatherMessage__DateTime, day),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Hour",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WeatherMessage__DateTime, has_hour),
    offsetof(WeatherMessage__DateTime, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Miunte",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WeatherMessage__DateTime, has_miunte),
    offsetof(WeatherMessage__DateTime, miunte),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Second",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WeatherMessage__DateTime, has_second),
    offsetof(WeatherMessage__DateTime, second),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather_message__date_time__field_indices_by_name[] = {
  2,   /* field[2] = Day */
  3,   /* field[3] = Hour */
  4,   /* field[4] = Miunte */
  1,   /* field[1] = Month */
  5,   /* field[5] = Second */
  0,   /* field[0] = Year */
};
static const ProtobufCIntRange weather_message__date_time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor weather_message__date_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WeatherMessage.DateTime",
  "DateTime",
  "WeatherMessage__DateTime",
  "",
  sizeof(WeatherMessage__DateTime),
  6,
  weather_message__date_time__field_descriptors,
  weather_message__date_time__field_indices_by_name,
  1,  weather_message__date_time__number_ranges,
  (ProtobufCMessageInit) weather_message__date_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor weather_message__field_descriptors[14] =
{
  {
    "Online",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WeatherMessage, has_online),
    offsetof(WeatherMessage, online),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Direction",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_direction),
    offsetof(WeatherMessage, direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MaxDir",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_maxdir),
    offsetof(WeatherMessage, maxdir),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MiniDir",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_minidir),
    offsetof(WeatherMessage, minidir),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Speed",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_speed),
    offsetof(WeatherMessage, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MaxSpeed",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_maxspeed),
    offsetof(WeatherMessage, maxspeed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MiniSpeed",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_minispeed),
    offsetof(WeatherMessage, minispeed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Temp",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_temp),
    offsetof(WeatherMessage, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Humi",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_humi),
    offsetof(WeatherMessage, humi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Rain",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_rain),
    offsetof(WeatherMessage, rain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Pressure",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_pressure),
    offsetof(WeatherMessage, pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Strength",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(WeatherMessage, has_strength),
    offsetof(WeatherMessage, strength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GPSdate",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(WeatherMessage, gpsdate),
    &weather_message__gps__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Date",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(WeatherMessage, date),
    &weather_message__date_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather_message__field_indices_by_name[] = {
  13,   /* field[13] = Date */
  1,   /* field[1] = Direction */
  12,   /* field[12] = GPSdate */
  8,   /* field[8] = Humi */
  2,   /* field[2] = MaxDir */
  5,   /* field[5] = MaxSpeed */
  3,   /* field[3] = MiniDir */
  6,   /* field[6] = MiniSpeed */
  0,   /* field[0] = Online */
  10,   /* field[10] = Pressure */
  9,   /* field[9] = Rain */
  4,   /* field[4] = Speed */
  11,   /* field[11] = Strength */
  7,   /* field[7] = Temp */
};
static const ProtobufCIntRange weather_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor weather_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WeatherMessage",
  "WeatherMessage",
  "WeatherMessage",
  "",
  sizeof(WeatherMessage),
  14,
  weather_message__field_descriptors,
  weather_message__field_indices_by_name,
  1,  weather_message__number_ranges,
  (ProtobufCMessageInit) weather_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
