/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ph3airmsg_2eproto__INCLUDED
#define PROTOBUF_C_ph3airmsg_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Ph3airmsg Ph3airmsg;


/* --- enums --- */


/* --- messages --- */

struct  _Ph3airmsg
{
  ProtobufCMessage base;
  protobuf_c_boolean has_online;
  int32_t online;
  protobuf_c_boolean has_ph3_ppm;
  int32_t ph3_ppm;
};
#define PH3AIRMSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ph3airmsg__descriptor) \
    , 0,0, 0,0 }


/* Ph3airmsg methods */
void   ph3airmsg__init
                     (Ph3airmsg         *message);
size_t ph3airmsg__get_packed_size
                     (const Ph3airmsg   *message);
size_t ph3airmsg__pack
                     (const Ph3airmsg   *message,
                      uint8_t             *out);
size_t ph3airmsg__pack_to_buffer
                     (const Ph3airmsg   *message,
                      ProtobufCBuffer     *buffer);
Ph3airmsg *
       ph3airmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ph3airmsg__free_unpacked
                     (Ph3airmsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ph3airmsg_Closure)
                 (const Ph3airmsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ph3airmsg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ph3airmsg_2eproto__INCLUDED */
